name: Terraform (Develop)

on:
  pull_request:
    branches-ignore: [main]
    paths-ignore:
      - 'bootstrap-wif/**'
  push:
    branches-ignore: [main]
    paths-ignore:
      - 'bootstrap-wif/**'

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:
  fmt_validate:
    name: Format & Validate
    runs-on: ubuntu-latest
    environment:
      name: Develop
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: true

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ./.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init (backend dev)
        run: |
          cd terraform
          terraform init \
            -backend-config=../configs/dev.config

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: [fmt_validate]
    if: github.event_name == 'pull_request'
    environment:
      name: Develop
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: true

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ./.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init (backend dev)
        run: |
          cd terraform
          terraform init \
            -backend-config=../configs/dev.config

      - name: Terraform Plan (env dev)
        run: |
          cd terraform
          terraform plan \
            -var-file=../environments/dev/terraform.tfvars \
            -input=false

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: [plan]
    if: github.event_name == 'push'
    environment:
      name: Develop
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: true

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ./.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init (backend dev)
        run: |
          cd terraform
          terraform init \
            -backend-config=../configs/dev.config

      - name: Terraform Apply (env dev)
        run: |
          cd terraform
          terraform apply \
            -auto-approve \
            -var-file=../environments/dev/terraform.tfvars \
            -input=false

  #deploy_app:
  #  name: Deploy Application
  #  runs-on: ubuntu-latest
  #  needs: [apply]
  #  if: github.event_name == 'push'
  #  environment:
  #    name: Develop
  #  permissions:
  #    contents: read
  #    id-token: write
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
#
  #    - name: Auth to Google Cloud (WIF)
  #      uses: google-github-actions/auth@v2
  #      with:
  #        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  #        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
#
  #    - name: Setup Google Cloud SDK
  #      uses: google-github-actions/setup-gcloud@v2
#
  #    - name: Configure Docker for GCR
  #      run: gcloud auth configure-docker
#
  #    - name: Build and Push Docker Image
  #      run: |
  #        cd kubernetes/simple-app
  #        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-app:latest .
  #        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-app:latest
#
  #    - name: Deploy to Kubernetes
  #      run: |
  #        gcloud container clusters get-credentials gke-cluster-dev --region europe-west9 --project ${{ secrets.GCP_PROJECT_ID }}
  #        cd kubernetes/simple-app
  #        sed "s/PROJECT_ID/${{ secrets.GCP_PROJECT_ID }}/g" k8s-deployment.yaml | kubectl apply -f -
  #        kubectl rollout status deployment/simple-app


